name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.0-beta1
          stable: false
      - name: "go vet"
        run: |
          go vet ./...
      - name: "go test"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          go test -cover -coverprofile coverage.txt -race -v ./...
      - uses: codecov/codecov-action@v1
